services:
    backend:
        build: .
        container_name: short-url-backend
        env_file:
            - .env
        ports:
            - "8000:8000"
        volumes:
            - ./src:/app/src  # 개발할때만 사용
            - logs:/app/logs
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - short-url-network
    mysql:
        image: mysql:8.0
        container_name: short-url-mysql
        env_file:
            - .env.mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - short-url-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 3

volumes:
    logs:
    mysql-data:

networks:
    short-url-network:
